### ISSUE TITLE
Newer kernel config options are not defined in config.x86_64

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [sfan5/pkgbuild-linux-bcachefs#1]
There are some new config options that the `config.x86_64` file does not seem to cover. Right now if I want to use the PKGBUILD, I have to manually set a bunch of options before I can compile the kernel. Most of it looks like drivers.

**Comment by sfan5** [comment]
The `bcachefs` repo was updated from 4.15 to 4.18 just 18 hours ago, I do not follow development closely and haven't gotten around to updating the PKGBUILD yet.
It's not like this breaks the build, overall low priority.

**Comment by DerVerruckteFuchs** [comment]
I figured as much considering I saw that one of the drivers was for the Steam controller, and that's been added as of 4.18. Some of the config options are a bit above my head, so I think I'll hold off on updating for now.
